### ISSUE TITLE
vcs/gitcmd does not build on HEAD

### ISSUE THREAD

**Issue by h8liu** [sourcegraph/go-vcs#100]
```
src/sourcegraph.com/sourcegraph/go-vcs/vcs/gitcmd/repo.go:1026:15: cannot use gitFSCmd literal (type *gitFSCmd) as type vfs.FileSystem in return argument:
	*gitFSCmd does not implement vfs.FileSystem (missing RootType method)
```

**Comment by h8liu** [comment]
detected by smallrepo:
https://smallrepo.com/builds/20180410-164259-71f9bf02

**Comment by shurcooL** [comment]
The `vfs.FileSystem` interface has changed (a new method was added) in https://github.com/golang/tools/commit/16d1af8d88c08b6a22e07a0900aad5279a7fb4fd. This is going to affect [quite a few packages](https://godoc.org/golang.org/x/tools/go/vcs?importers) that implement that interface.

The simplest initial fix is to add the new `RootType` method. It's only needed for `godoc` operation, so the implementation can be trivial:

```Go
func (*gitFSCmd) RootType(string) vcs.RootType { return vcs.RootTypeStandAlone }
```

Next, the decision to use the `vfs.FileSystem` interface from a `godoc`-related package can be reconsidered.

**Comment by shurcooL** [comment]
I've sent PR #101 that fixes the build.
