### ISSUE TITLE
vcs/git (native): No support for annotated tags.

### ISSUE THREAD

**Issue by dmitshur** [sourcegraph/go-vcs#24]
If you look at `GetCommit` and `FileSystem` implementations of `vcs/git` package, they both use `LookupCommit`, which doesn't work when the object is an annotated tag rather than a commit.

`ResolveTag` returns the tag's `CommitId`, rather than its parent. So I see no way to get a working `FileSystem` for a given annotated tag.

**Comment by shurcooL** [comment]
`vcs/git` implementation has been replaced with a pure Go based implementation. Is this still a valid issue?

**Comment by shurcooL** [comment]
The test program from sourcegraph/vcsstore#11 updated to use the new import paths and to try to walk the filesystem (source [here](http://play.golang.org/p/4n_PalnY5K)), now prints:

```Go
commit = (*vcs.Commit)(&vcs.Commit{
	ID: (vcs.CommitID)("f8d048baeca3571b825c647ce6bdc59f9fbf004f"),
	Author: (vcs.Signature)(vcs.Signature{
		Name:  (string)(""),
		Email: (string)(""),
		Date: (pbtypes.Timestamp)(pbtypes.Timestamp{
			Seconds: (int64)(0),
			Nanos:   (int32)(0),
		}),
	}),
	Committer: (*vcs.Signature)(nil),
	Message:   (string)("Version 1 Release"),
	Parents:   ([]vcs.CommitID)(nil),
})
2016/02/03 00:16:02 can't stat file /: commit.Author was nil, which may be unexpected
```

Which seems reasonable and better than the previous output:

```
panic: The requested type does not match the type in the ODB
```

But it may not be enough to resolve the underlying issue, it's still not possible to access the `FileSystem` of an annotated tag, is there?
