### ISSUE TITLE
Ability to get the raw change of a commit?

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/go-vcs#75]
Looking at the [`vcs.Repository` interface](https://godoc.org/sourcegraph.com/sourcegraph/go-vcs/vcs#Repository), I see no way to get just the raw diff of a single specified commit. I was always under the impression this package supported that, but `GetCommit` returns `*vcs.Commit` which only has commit message, author, etc., but not the actual commit diff itself.

I don't see it under any optional interfaces either. The only thing that returns a `*Diff` is `vcs.Differ` and `vcs.CrossRepoDiffer`, but those are meant to get a diff between two distinct commits, not the change of a single commit.

Just wanted to confirm if that's the case and I'm not overlooking something very obvious.

**Comment by sqs** [comment]
What about just doing a diff of c and c~1 or c^1? You want something like git show, right?

**Comment by shurcooL** [comment]
> You want something like git show, right?

Yes, exactly.

> What about just doing a diff of c and c~1 or c^1?

That's the only way I could think of doing it so far, but I was afraid it might be not as efficient as a more dedicated approach.

I primarily wanted to confirm there's not something simpler/more direct/efficient that I was overlooking. Thanks.

**Comment by sqs** [comment]
Nope, not that I can think of.

`git show` would be useful
