### ISSUE TITLE
Proposal: Add UpdateResult to UpdateEverything method.

### ISSUE THREAD

**Issue by shurcooL** [sourcegraph/go-vcs#79]
This is an early first draft of a proposal. It comes with a sample implementation, but it's very easy to refactor and change it.

#### Background

There are situations where just updating the remote with `UpdateEverything` method and know if it succeeded is not enough, and it's desirable to know a few additional things:

- Has anything changed at all?
- More specifically, have any branches been added, deleted, or updated?

That can enable, e.g., updating the UI when repo updates/changes are available.

# Proposal

I propose having a way to perform a remote update and returning the results of the operation, which contains the changes to branches, if any.

There are 2 ways I see of doing so:

1. Add another interface and method, e.g., `UpdateEverythingResult`, which returns `(UpdateResult, error)`. This is a non-API-breaking change, but it results in two very similar methods.
    - It's possible to then deprecate `UpdateEverything` method and remove it after some time.

2. Change `UpdateEverything` method (and therefore `RemoteUpdater` interface) to have an additional return value, so it returns `(UpdateResult, error)` instead of just `error` as it currently does.

3. (Implicit extra option.) This proposal can be rejected altogether.

I think I would prefer going with the 2nd approach, because this library's API is not yet frozen, and I see this as an overall improvement of the API.

Thoughts?

### Current Implementation

See https://github.com/sourcegraph/go-vcs/pull/80.

**Comment by shurcooL** [comment]
Hi,

It's been 5 days - is there anything I can do to help get feedback and be able to move forward on this? :)

Thanks!

**Comment by slimsag** [comment]
I've given this some thought and while I don't have 100% context (up to your confidence on whether or not you want to get a second opinion), I feel the second approach is cleaner and overall nicer in the long run.

I also left some comments on your initial implementation, some very obvious, but overall it is looking good.

**Comment by shurcooL** [comment]
> I feel the second approach is cleaner and overall nicer in the long run.

I agree.

In support of that, I'd like to point to [exhibit A][1]. It's a change to go-sourcegraph API that is very similar in nature. It changes a method `Merge` from returning `void` to returning `ChangesetEvent` which contains information about the result of the operation.

[1]: https://github.com/sourcegraph/go-sourcegraph/pull/86

**Comment by beyang** [comment]
:+1: to option 2

**Comment by beyang** [comment]
Actually, not so sure anymore. I don't think the correct behavior for implementations that don't yet parse the result should be to return an empty result. This is invisible and misleading to the client. Counter-proposal:
- Pass an extra option field to the `RemoteOpts` struct that makes it explicit you are requesting the VCSResult. If the implementation does not support this, then it must return an "operation not supported" error.

**Comment by shurcooL** [comment]
I like that idea @beyang.

In that case, I'll probably make the `VCSResult` return a pointer.

Also, instead of adding that option to `RemoteOpt`, which is a common struct used by `CloneOpt` as well, I should create a `UpdateOpt` and have it there:

```Go
// CloneOpt is options for Clone method.
type CloneOpt struct {
	Bare   bool // create a bare repo
	Mirror bool // create a mirror repo (`git clone --mirror`)

	RemoteOpts // configures communication with the remote repository
}

// UpdateOpt is options for UpdateEverything method.
type UpdateOpt struct {
	ParseResult bool // parses results of operation and returns a non-nil VCSResult

	RemoteOpts // configures communication with the remote repository
}
```

How's that?

My only concern is that parsing the result of an update operation is insignificant computationally-wise compared to performing a remote update. Having to set an options bool makes sense for optional things that are computationally hard to achieve.

The only reason we're tempted to do this now is because other backends do not have it implemented.

An analogy I can make is that it'd be like making `io.Writer` to be:

```Go
type Writer interface {
	Write(p []byte, opt WriteOptions) (n *int, err error)
}

type WriteOptions {
	CalculateNumberOfBytesWritten
}
```

That'd a much less convenient API than the actual `io.Writer`, where if you don't care about `n`, you can just write:

```Go
_, err := w.Write(b)
```

Since each of these changes is going to be a breaking API change, I'm starting to think we should optimize for ideal end-target go-vcs API, rather than optimize the API for what current implementations happen to support. That's what the [compatibility table](https://github.com/sourcegraph/go-vcs#implementation-differences) is for. Especially because this interface is optionally implemented, so when changed, places that rely on it won't be caught by type checker, so changing it is more expensive than a non-optional interface like `vcs.Repository`.

And IMO the nicest long term API here is indeed what #80 has:

```Go
// A RemoteUpdater is a repository that can fetch updates to itself
// from a remote repository.
type RemoteUpdater interface {
	// UpdateEverything updates all branches, tags, etc., to match the
	// default remote repository. The implementation is VCS-dependent.
	// If supported by the implementation, results of update will be returned.
	UpdateEverything(RemoteOpts) (UpdateResult, error)
}
```

Note that the documentation says "If supported by the implementation, results of update will be returned."

A compromise could be:

```Go
UpdateEverything(RemoteOpts) (*UpdateResult, error)
```

But that would also be sub-optimal as soon as all implementations support this feature.

Thoughts?

**Comment by shurcooL** [comment]
Although the key difference between my `Write(p []byte, opt WriteOptions) (n *int, err error)` analogy and `UpdateEverything(RemoteOpts) (UpdateResult, error)` is that, while the result in both cases is computationally inexpensive to compute, returning `n` is very easy for all implementations of `io.Writer` to implement. On the other hand, returning a valid `UpdateResult` is a lot harder to implement.

**Comment by beyang** [comment]
I like `UpdateEverything(RemoteOpts) (*UpdateResult, error)`, with the docs explicitly mentioning that when the first return value is not nil, then the client can treat that as an actual result. Alternatively, you could add a third return value that signals whether the return value was parsed by the method, but that seems uglier than returning a pointer.

**Comment by shurcooL** [comment]
Yeah, perhaps that compromise is the best option to go with.

Having the pointer is a little ugly and unnecessary if all implementations return a valid `UpdateResult`, but realistically speaking, since it's difficult to implement, it's likely some implementations will not implement this for a long time. So perhaps that's the best thing to optimize this API for.

**Comment by shurcooL** [comment]
@beyang made an excellent point:

> the client might not necessarily know which implementation is being called under the hood

So providing information in the docs and compatibility table is not enough. Unless each implementation implements this interface only if it can implement it fully, it would need some other way to indicate whether or not it populated the `UpdateResult` value. Making it a pointer is one way of making that possible.

By now, I am starting to reconsider idea 1, to have a new, separate optional interface:

```
UpdateEverythingWithResult(UpdateResult, error)
```

Having a different interface means implementation can communicate whether or not they've implemented the functionality... by implementing (or not) the interface.

Since it's hard to implement for all vcs backends, perhaps it's the right thing to do now.

As an added benefit, it will not be a breaking API change.

**Comment by beyang** [comment]
I think the pointer option is better still, since it saves adding another method to the interface. Also, I think all implementations will have to implement this method, anyway, because the interface that contains this method will be the one that gets passed around everywhere in code. And then you're back to the case of returning an error when an implementation doesn't actually support the method.

**Comment by shurcooL** [comment]
> Also, I think all implementations will have to implement this method, anyway, because the interface that contains this method will be the one that gets passed around everywhere in code.

What do you mean? This method is not a part of the main `vcs.Repository` interface. It's a part of a standalone interface:

```Go
// A RemoteUpdater is a repository that can fetch updates to itself
// from a remote repository.
type RemoteUpdater interface {
	// UpdateEverything updates all branches, tags, etc., to match the
	// default remote repository. The implementation is VCS-dependent.
	UpdateEverything(RemoteOpts) error
}
```

To use it, you always have to check if it's implemented. E.g.:

```Go
if ru, ok := repo.(vcs.RemoteUpdater); ok {
	err := ru.UpdateEverything(vcs.RemoteOpts{})
	// Check err.
}
```

Ah, I think I see your point. The *update* functionality of this interface is pretty core. That's why a lot of code now just assumes this is implemented and does:

```
err := repo.(vcs.RemoteUpdater).UpdateEverything(vcs.RemoteOpts{})
// Check err.
```

So each backend would have to implement at least `vcs.RemoteUpdater`, but maybe also `vcs.RemoteUpdaterWithResult`. Hmm.

**Comment by shurcooL** [comment]
Ok, I'm starting to converge on the pointer (to indicate optionally returned value) approach:

```Go
// A RemoteUpdater is a repository that can fetch updates to itself
// from a remote repository.
type RemoteUpdater interface {
	// UpdateEverything updates all branches, tags, etc., to match the
	// default remote repository. The implementation is VCS-dependent.
	// If supported by the implementation, results of update will be returned, otherwise it'll be nil.
	UpdateEverything(RemoteOpts) (*UpdateResult, error)
}
```

**Comment by beyang** [comment]
LGTM

**Comment by shurcooL** [comment]
@beyang, you've said "LGTM" to the proposal here. I've updated the implementation in #80 to match (see last commit). Does it have your LGTM?

**Comment by beyang** [comment]
LGTM

**Comment by shurcooL** [comment]
I assume you meant to post that in the PR, right? Hehe.
